create table if not exists public.processed_webhooks (
  id bigint generated by default as identity primary key,
  message_id text not null unique,
  wa_id text not null,
  payload jsonb,
  processed_at timestamptz not null default now()
);

create index if not exists idx_processed_webhooks_wa_id on public.processed_webhooks (wa_id);
create index if not exists idx_processed_webhooks_processed_at on public.processed_webhooks (processed_at desc);
