'use client';

import { motion } from 'framer-motion';
import { ResponsiveContainer, BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, Cell } from 'recharts';
import DemoSidebar from '@/components/demo/DemoSidebar';

const reports = [
  {
    month: 'March 2026',
    metrics: ['34 keywords improved', '8 new top-10 rankings', '12 backlinks', '9 articles'],
  },
  {
    month: 'February 2026',
    metrics: ['28 keywords improved', '5 new top-10 rankings', '9 backlinks', '8 articles'],
  },
  {
    month: 'January 2026',
    metrics: ['19 keywords improved', '3 new top-10 rankings', '7 backlinks', '7 articles'],
  },
];

const growthData = [
  { month: 'Jan', value: 19, projected: false },
  { month: 'Feb', value: 28, projected: false },
  { month: 'Mar', value: 34, projected: false },
  { month: 'Apr', value: 0, projected: true },
  { month: 'May', value: 0, projected: true },
  { month: 'Jun', value: 0, projected: true },
];

export default function ReportsPage() {
  return (
    <div className="flex min-h-screen bg-[#0A0B0F] text-[#F0F2F8]">
      <DemoSidebar />
      <main className="flex-1 overflow-y-auto p-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-[1200px] mx-auto">
          <h1 className="text-3xl font-bold mb-2">Reports</h1>
          <p className="text-[#8892A4] mb-8">Monthly performance summaries</p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8">
            {reports.map((r) => (
              <div key={r.month} className="bg-[#12141A] border border-[#1E2130] rounded-xl p-5">
                <h2 className="text-xl font-semibold mb-1">{r.month}</h2>
                <p className="text-sm text-[#8892A4] mb-4">Generated by PULSE + ARIA</p>
                <ul className="space-y-2 mb-5 text-sm">
                  {r.metrics.map((m) => (
                    <li key={m} className="flex items-center gap-2">
                      <span className="text-[#1D9E75]">✓</span>
                      <span>{m}</span>
                    </li>
                  ))}
                </ul>
                <div className="flex gap-2">
                  <button className="flex-1 border border-[#1D9E75]/50 text-[#1D9E75] rounded-lg py-2 text-sm">Download PDF</button>
                  <button className="flex-1 bg-[#7F77DD] text-white rounded-lg py-2 text-sm">View Full Report</button>
                </div>
              </div>
            ))}
          </div>

          <div className="bg-[#12141A] border border-[#1E2130] rounded-xl p-5 mb-8">
            <h2 className="text-lg font-semibold mb-3">6-Month Keyword Growth</h2>
            <ResponsiveContainer width="100%" height={280}>
              <BarChart data={growthData}>
                <CartesianGrid stroke="#1E2130" strokeDasharray="3 3" />
                <XAxis dataKey="month" stroke="#8892A4" />
                <YAxis stroke="#8892A4" label={{ value: 'Keywords Improved', angle: -90, position: 'insideLeft', fill: '#8892A4' }} />
                <Tooltip contentStyle={{ background: '#12141A', border: '1px solid #1E2130' }} />
                <Bar dataKey="value" radius={[6, 6, 0, 0]}>
                  {growthData.map((entry) => (
                    <Cell key={entry.month} fill={entry.projected ? '#7F77DD55' : '#7F77DD'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
            <div className="text-xs text-[#8892A4] mt-2">Apr-Jun are projected</div>
          </div>

          <div className="bg-[#12141A] border border-[#1E2130] rounded-xl p-5">
            <h2 className="text-lg font-semibold mb-4">Executive Summary</h2>
            <ul className="space-y-2 text-sm">
              <li className="flex items-start gap-2"><span className="text-[#1D9E75]">•</span><span>Domain Authority improved from 34 to 41 — a 20% increase in 90 days</span></li>
              <li className="flex items-start gap-2"><span className="text-[#1D9E75]">•</span><span>Dental clinic andheri west keyword reached position #3 — from position #14</span></li>
              <li className="flex items-start gap-2"><span className="text-[#1D9E75]">•</span><span>GBP rating improved from 4.2 to 4.6 stars — 73% more clicks vs 3.9-star competitors</span></li>
            </ul>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
