/**
 * Runtime Contracts Index
 * 
 * Central export point for all runtime contracts
 * These contracts are framework-agnostic, database-agnostic, queue-agnostic abstractions
 * for workflow engines, workers, AI agents, queues, schedulers, and distributed execution systems
 */

// Execution contract
export {
  ExecutionStatus,
} from './execution.contract';
export type {
  ExecutionId,
  ExecutionContext,
  ExecutionResult,
  ExecutionMetrics,
  ExecutionError,
  ExecutionCheckpoint,
  ExecutionOptions,
  ExecutionProgress,
  WorkflowExecutionEngine,
  ExecutionInfo,
  ExecutionFilter,
} from './execution.contract';

// Task contract
export {
  TaskStatus,
} from './task.contract';
export type {
  TaskId,
  TaskType,
  TaskPriority,
  TaskExecutionContext,
  TaskExecutionResult,
  TaskError,
  TaskMetrics,
  TaskCheckpoint,
  TaskOptions,
  TaskProgress,
  TaskDefinition,
  RuntimeTaskExecutor,
  ValidationResult,
  TaskExecutorFactory,
  TaskScheduler,
  TaskFilter,
  TaskInfo,
  TaskQueueStatus,
} from './task.contract';

// Worker contract
export type {
  WorkerId,
  WorkerStatus,
  WorkerType as BaseWorkerType,
  WorkerCapabilities,
  WorkerConfig,
  WorkerState,
  WorkerError,
  WorkerMetrics,
  WorkerHeartbeat,
  RuntimeWorker,
  WorkerTaskResult,
  WorkerTaskError,
  WorkerTaskMetrics,
  WorkerHealthStatus,
  WorkerPool,
  TaskDispatchOptions,
  // Worker contract removed in Phase 2A.2 - V1 prohibits distributed workers
  // WorkerPoolStatus,
  // WorkerPoolMetrics,
  // WorkerFactory,
  // WorkerPoolConfig,
} from './worker.contract';

// Event contract
export type {
  EventId,
  EventType,
  EventSource,
  EventVersion,
  CorrelationId,
  CausationId,
  TraceId,
  SpanId,
  RuntimeEvent,
  EventEnvelope,
  EventHeaders,
  EventFilter,
  EventPublisher,
  EventPublishResult,
  EventPublishError,
  EventSubscriber,
  EventHandler,
  EventHandleResult,
  EventHandleError,
  SubscriptionId,
  Subscription,
  EventStream,
  EventStore,
  EventStoreResult,
  EventStoreError,
  EventTracer,
  SpanContext,
  TraceContext,
  Trace,
  Span,
  SpanLog,
  EventCorrelation,
} from './event.contract';

// Recovery contract
export type {
  RecoveryStrategy,
  RecoveryStatus,
  RecoveryScope,
  RecoveryTrigger,
  RecoveryContext,
  FailureInfo,
  RecoveryResult,
  RecoveryError,
  RecoveryMetrics,
  RecoveryOptions,
  RecoveryProgress,
  RecoveryWorkflow,
  RecoveryEligibility,
  RecoveryConstraints,
  RecoveryPolicy,
  RecoveryCondition,
  RecoveryPolicyEngine,
  PolicyEvaluationResult,
  PolicyFilter as RecoveryPolicyFilter,
  RollbackManager,
  RollbackResult,
  RollbackError,
  RollbackStatus,
  RollbackEligibility,
  CompensationManager,
  CompensationResult,
  CompensationError,
  CompensationStatus,
  CompensationEligibility,
  RecoveryCoordinator,
  RecoveryCandidate,
  RecoveryCandidateFilter,
  RecoveryStatistics,
} from './recovery.contract';

// Checkpoint contract
export type {
  CheckpointId,
  CheckpointType,
  CheckpointStatus,
  RuntimeCheckpoint,
  CheckpointState,
  CheckpointMetadata,
  CheckpointOptions,
  CheckpointResult,
  CheckpointError,
  CheckpointManager,
  CheckpointRestoreResult,
  CheckpointValidationResult,
  CheckpointFilter,
  CheckpointStorage,
  CheckpointStorageResult,
  CheckpointStorageError,
  CheckpointSerializer,
  SerializedCheckpoint,
  CompressedCheckpoint,
  EncryptedCheckpoint,
  CheckpointPolicy,
  CheckpointPolicyManager,
  PolicyEvaluationResult as CheckpointPolicyEvaluationResult,
  CheckpointMetrics,
  CheckpointStatistics,
} from './checkpoint.contract';

// Runtime errors contract
export type {
  ErrorCode,
  ErrorSeverity,
  ErrorCategory,
  RuntimeExecutionError,
  ErrorDetails,
  ErrorContext,
  ErrorResult,
  ErrorHandlingStrategy,
  ErrorHandlingError,
  ErrorHandler,
  ErrorHandlingRecord,
  ErrorStatisticsFilter,
  ErrorStatistics,
  ErrorReporter,
  ErrorReportResult,
  ErrorReportError,
  ErrorReportFilter,
  TimeRange as ErrorTimeRange,
  ErrorTrends,
  ErrorClassifier,
  ErrorClassification,
  ErrorClassificationRule,
  ErrorClassificationCondition,
  ErrorAggregator,
  ErrorAggregation,
  ErrorAggregationSummary,
  ErrorAggregationFilter,
  AggregationStatistics,
  ErrorNotifier,
  ErrorNotificationResult,
  ErrorNotificationError,
  ErrorNotificationFilter,
  ErrorNotificationHandler,
  ErrorRecoveryAdvisor,
  RecoveryAdvice,
  RecoveryStep,
  RecoveryAction,
} from './runtime-errors.contract';

// Runtime identity contract
export type {
  RuntimeIdentity,
  IdentityType,
  IdentityMetadata,
  RuntimeNode,
  NodeType as RuntimeIdentityNodeType,
  NodeAddress,
  NodeCapabilities,
  ExecutionType,
  ResourceLimits as IdentityResourceLimits,
  NodeStatus as RuntimeIdentityNodeStatus,
  NodeMetadata as RuntimeIdentityNodeMetadata,
  RuntimeInstance,
  InstanceType,
  InstanceConfiguration,
  InstanceStatus,
  InstanceMetadata,
  WorkerInstance,
  WorkerType as IdentityWorkerType,
  WorkerCapabilities as IdentityWorkerCapabilities,
  WorkerStatus as IdentityWorkerStatus,
  WorkerMetadata as IdentityWorkerMetadata,
  ExecutionLease,
  LeaseMetadata as IdentityLeaseMetadata,
  LeaseType,
  LeasePriority,
  OwnershipToken,
  ResourceType as IdentityResourceType,
  OwnershipMetadata,
  OwnershipType,
  DistributedOwnership,
  OwnershipTransferResult,
  OwnershipReleaseResult,
  OwnershipValidationResult,
  OwnershipError,
  ExecutionLeasing,
  LeaseAcquisitionOptions,
  LeaseAcquisitionResult,
  LeaseRenewalResult as IdentityLeaseRenewalResult,
  LeaseReleaseResult,
  LeaseTransferResult,
  LeaseValidationResult,
  WorkerOwnership,
  WorkerOwnershipOptions,
  WorkerOwnershipAcquisitionResult,
  WorkerOwnershipReleaseResult,
  WorkerOwnershipTransferResult,
  WorkerOwnershipValidationResult,
  FailoverSemantics,
  FailoverReason as IdentityFailoverReason,
  FailoverResult,
  FailoverStatus,
  FailoverCandidate,
  ReadinessStatus as IdentityReadinessStatus,
  CandidateMetadata as IdentityCandidateMetadata,
  ReplayOwnership,
  ReplayOwnershipOptions,
  ReplayOwnershipAcquisitionResult,
  ReplayOwnershipReleaseResult,
  ReplayOwnershipValidationResult,
  ExecutionAffinity,
  AffinityOptions,
  AffinityType as IdentityAffinityType,
  AffinityResult,
  AffinityRule,
} from './runtime-identity.contract';

// Coordination contract
export type {
  CoordinationProvider,
  DistributedLock,
  LeaseManager,
  HeartbeatCoordinator,
  ConsensusContext,
  LockStatus,
  LockOptions,
  LockMetadata,
  LockAcquisitionOptions,
  LockAcquisitionResult,
  LockReleaseResult,
  LockExtensionResult,
  LockInfo,
  LeaseStatus as CoordinationLeaseStatus,
  LeaseManagerOptions,
  LeaseMetadata as CoordinationLeaseMetadata,
  LeaseAcquisitionOptions as CoordinationLeaseAcquisitionOptions,
  LeaseAcquisitionResult as CoordinationLeaseAcquisitionResult,
  LeaseReleaseResult as CoordinationLeaseReleaseResult,
  LeaseRenewalResult as CoordinationLeaseRenewalResult,
  LeaseExtensionResult,
  LeaseInfo,
  ParticipantOptions,
  ParticipantMetadata,
  ParticipantRegistrationResult,
  ParticipantUnregistrationResult,
  HeartbeatResult,
  ParticipantStatus,
  ParticipantHealth,
  CoordinatorInfo,
  HeartbeatCoordinatorOptions,
  ConsensusStatus,
  ConsensusContextOptions,
  ConsensusMetadata,
  ProposalOptions,
  ProposalMetadata,
  ProposalResult,
  AcceptanceResult,
  RejectionResult,
  ConsensusResult,
  ContextInfo,
  LockOwnership,
  LockTransferResult,
  LockOwnershipValidationResult,
  LeaderElection,
  ElectionStatus,
  ElectionOptions,
  ElectionMetadata,
  ElectionParticipationResult,
  ElectionWithdrawalResult,
  ElectionInfo,
  CoordinationError,
  CoordinationHealthStatus,
  FailoverCoordination,
  FailoverReason as CoordinationFailoverReason,
  FailoverCoordinationResult,
  FailoverCoordinationStatus,
  FailoverState,
  FailoverCandidate as CoordinationFailoverCandidate,
  ReadinessStatus as CoordinationReadinessStatus,
  CandidateMetadata as CoordinationCandidateMetadata,
} from './coordination.contract';

// Version contract
export type {
  SemanticVersion,
  RuntimeContractVersion,
  ContractType,
  CompatibilityLevel,
  CompatibilityMatrix,
  MigrationMetadata,
  MigrationType,
  DataLossRisk,
  ContractMetadata,
  DeprecationInfo,
  StabilityLevel,
  VersionedContract,
  ContractRegistry,
  ValidationResult as VersionValidationResult,
  VersionComparison,
  VersionComparator,
  VersionRange,
  ContractEvolutionPolicy,
  EvolutionStrategy,
  ContractValidator,
} from './version.contract';

// Capability contract
export type {
  CapabilityType,
  CapabilityLevel,
  CapabilityDescriptor,
  CapabilityConstraints,
  RuntimeCapabilities,
  WorkerCapabilities as CapabilityWorkerCapabilities,
  ExecutionCapabilities,
  StreamingCapabilities,
  StreamType as CapabilityStreamType,
  RecoveryCapabilities,
  TracingCapabilities as CapabilityTracingCapabilities,
  ResourceProfile,
  CapabilityNegotiation,
  NegotiationStrategy as CapabilityNegotiationStrategy,
  CapabilityMatchResult,
  PartialCapabilityMatch,
  NegotiationResult as CapabilityNegotiationResult,
  CapabilityRegistry,
  CompatibilityValidationResult as CapabilityCompatibilityValidationResult,
  CapabilityQuery,
  CapabilityDiscovery,
  ValidationResult as CapabilityValidationResult,
  CapabilityProvider,
  CapabilityContext,
  CapabilityProvisionResult,
  CapabilityProvisionError,
  CapabilityStatus,
  CapabilityUsageStats,
} from './capability.contract';

// Stream contract
export type {
  StreamType as StreamStreamType,
  StreamEventType,
  RuntimeStreamChunk,
  StreamChunkMetadata,
  TokenStreamChunk,
  ProgressStreamChunk,
  EventStreamChunk,
  LogStreamChunk,
  OutputStreamChunk,
  RuntimeStream,
  StreamStatus as ContractStreamStatus,
  StreamMetadata,
  RuntimeStreamController,
  BackpressureStatus,
  StreamReader,
  StreamChunkHandler,
  StreamSubscriptionOptions,
  StreamChunkFilter,
  StreamSubscription,
  StreamFactory,
  StreamFilter,
  StreamResumption,
  StreamCheckpoint,
  ResumptionCapability,
  ResumptionValidationResult,
  StreamMetrics,
  StreamMetricsCollector,
  AggregateStreamMetrics,
} from './stream.contract';

// Determinism contract
export type {
  DeterminismLevel,
  ExecutionSeed,
  SeedAlgorithm,
  SeedScope,
  DeterministicExecutionContext,
  ReplaySource,
  ReplaySourceType,
  ReplayContext,
  ReplayStrategy,
  ReplayPoint,
  ReplayPointType,
  ReplayResult,
  DivergenceReport,
  DivergencePoint as DeterministicDivergencePoint,
  DivergenceRootCause,
  DivergenceCauseType,
  ReplayError,
  DeterministicExecutionEngine,
  DeterministicExecutionResult,
  DeterminismReport,
  DeterministicExecutionError,
  DeterminismValidationResult,
  DeterminismViolation,
  DeterminismViolationType,
  ExecutionSnapshot,
  ExecutionState,
  SnapshotRestoreResult as DeterministicSnapshotRestoreResult,
  SnapshotRestoreError as DeterministicSnapshotRestoreError,
  ExecutionComparisonResult,
  ExecutionDifference,
  DifferenceType,
  ComparisonSummary,
  AuditReplay,
  AuditReplayOptions,
  AuditReplayResult,
  AuditReplayError,
  AuditLog,
  AuditStep,
  AuditValidationResult,
  StepReplayResult,
} from './determinism.contract';

// Resource contract
export type {
  ResourceType as ContractResourceType,
  ResourceUnit,
  ResourceLimit,
  EnforcePolicy as ResourceEnforcePolicy,
  RuntimeResourceLimits,
  EnforcementStrategy,
  ResourceConsumption,
  ResourceConsumptionSnapshot,
  TotalResourceConsumption,
  ResourceConsumptionSummary,
  ExecutionQuota,
  QuotaScope,
  QuotaPeriod,
  QuotaWarning,
  WorkerResourceProfile,
  ResourceCapacity,
  ResourceCapacityValue,
  ResourceUtilization,
  ResourceAllocation,
  AllocationStatus,
  ResourceConstraints,
  ResourceAffinity,
  ResourceManager,
  ResourceScope,
  AvailabilityResult,
  EnforcementResult,
  EnforcementAction,
  ResourceQuotaManager,
  QuotaCheckResult,
  QuotaFilter,
  ResourceMonitoring,
  ResourceMetrics,
  TimeRange as ResourceTimeRange,
  ResourceTrends,
  ResourceUtilizationTrends,
  TrendData,
  ResourceConsumptionTrends,
  ResourcePredictions,
  ResourceAlert,
  AlertType,
  MetricsHandler,
  SubscriptionId as ResourceSubscriptionId,
} from './resource.contract';

// Scheduling contract - removed (adapters directory does not exist)

// State machine contract
export type {
  State,
  StateMetadata,
  StateTransition,
  TransitionGuard,
  GuardType,
  GuardCondition,
  ConditionType as StateConditionType,
  ComparisonOperator as StateComparisonOperator,
  TransitionAction,
  ActionType as StateActionType,
  TransitionMetadata,
  StateSnapshot,
  TransitionRecord,
  TransitionError,
  StateMachineContext,
  RuntimeStateMachine,
  StateMachineType,
  StateMachineInitializationResult,
  StateTransitionResult,
  TransitionValidationResult,
  GuardResult,
  SnapshotRestoreResult as StateMachineSnapshotRestoreResult,
  SnapshotRestoreError as StateMachineSnapshotRestoreError,
  StateMachineError,
  StateMachineBuilder,
  StateMachineValidationResult,
  StateMachineRegistry,
  StateMachineFilter,
  StateMachineObserver,
  TransitionEventHandler,
  StateChangeHandler,
  GuardFailureHandler,
  SubscriptionId as StateSubscriptionId,
  TransitionEvent,
  StateChangeEvent,
  GuardFailureEvent,
  TransitionEventFilter,
  HierarchicalStateMachine,
  ParallelStateMachine,
  ParallelRegion,
  ParallelExecutionResult,
  RegionExecutionResult,
  SynchronizationResult,
  SynchronizationConflict,
  ConflictType,
} from './state-machine.contract';
