/**
 * Runtime Adapters Layer Index
 * 
 * Central export point for all adapter contracts
 * Enforces explicit exports and prevents dependency leakage
 */

// Types
export type {
  AdapterId,
  ProviderId,
  AdapterHealth,
  AdapterError,
  AdapterConfiguration as BaseAdapterConfiguration,
  AdapterCapabilities as BaseAdapterCapabilities,
  AdapterLimitation as BaseAdapterLimitation,
  AdapterRequirement as BaseAdapterRequirement,
  AdapterLifecycle,
  ConnectionOptions,
  SecurityOptions,
  AuthenticationConfig,
  EncryptionConfig,
  TLSConfig,
  RetryOptions,
  TimeoutOptions,
  SerializationOptions,
  ProviderMetadata as BaseProviderMetadata,
} from './types';

// Types runtime values (enums)
export {
  AdapterType,
  ProviderType,
  AdapterStatus,
} from './types';

// Queue adapters
export type {
  QueueAdapter,
  QueueProvider,
  QueueMessage,
  QueueLease,
  QueueConsumer,
  QueuePublisher,
  QueueCapabilities,
  QueueAdapterConfig,
  QueueConnectionOptions,
  QueueOptions,
  QueueConsumerOptions,
  QueueProducerOptions,
  QueuePublishOptions,
  QueueConsumeOptions,
  QueueMessageFilter,
  QueueRejectOptions,
  QueuePublishResult,
  QueueError,
  QueueHealthStatus,
  QueueConfigValidationResult,
  QueueProviderMetadata,
  QueueConsumerStatistics,
  QueuePublisherStatistics,
} from './queue/queue.contract';

// Queue runtime values (enums)
export {
  QueueDeliverySemantics,
  QueueAcknowledgmentSemantics,
  QueueOrdering,
  QueueConsumerStatus,
} from './queue/queue.contract';

// Event bus adapters
export type {
  EventBusAdapter,
  EventTransport,
  EventSubscription,
  EventChannel,
  RuntimeEvent,
  EventHeaders,
  EventMetadata,
  EventBusCapabilities,
  EventBusAdapterConfig,
  TopicOptions,
  SubscriptionOptions,
  EventPublishOptions,
  EventFilter,
  EventHandler,
  EventPublishResult,
  EventError,
  TopicInfo,
  TopicFilter,
  EventBusHealthStatus,
  EventProvider,
  EventConfigValidationResult,
  EventProviderMetadata,
  EventConsumer,
  EventConsumerStatistics,
  EventPublisher,
  EventPublisherStatistics,
} from './events/event-bus.contract';

// Event bus runtime values (enums)
export {
  EventTransportType,
  ConnectionStatus as EventConnectionStatus,
  SubscriptionStatus as EventSubscriptionStatus,
  ChannelType,
  EventRoutingStrategy,
  EventDeliveryGuarantee,
  EventOrderingGuarantee,
  EventCompression,
  EventConsumerStatus,
} from './events/event-bus.contract';

// Event bus aliased types
export type {
  EventConnectionOptions as EventBusConnectionOptions,
  PublisherOptions as EventPublisherOptions,
  EventSubscriptionOptions as EventBusSubscriptionOptions,
} from './events/event-bus.contract';

// Tracing adapters
export type {
  TracingAdapter,
  TraceProvider,
  SpanExporter,
  RuntimeTrace,
  TraceState,
  TraceBaggage,
  RuntimeSpan,
  SpanKind,
  SpanStatus,
  SpanStatusCode,
  SpanAttributes,
  SpanEvent,
  SpanLink,
  SpanResource,
  TraceConfigValidationResult,
  TraceProviderMetadata,
  SpanExportResult,
  TraceError,
  TracePropagationStrategy,
  ContextFormat,
  TraceOptions,
  SpanOptions,
  Exception,
  TracingCapabilities,
  TracingAdapterConfig,
  AdapterServiceConfig as ServiceConfig,
  ExporterConfig,
  ExporterType,
  SamplerConfig,
  SamplerType,
  PropagationConfig,
  TracingHealthStatus,
  DeterministicReplayMarker,
  ReplayMode,
  ReplayAwareTracing,
  ReplayConsistencyResult,
  DivergencePoint,
} from './tracing/tracing.contract';

// Checkpoint storage adapters
export type {
  CheckpointStorageAdapter,
  CheckpointSerializer,
  CheckpointCompressor,
  CheckpointEncryptor,
  CheckpointRetentionPolicy,
  StoredCheckpoint,
  CheckpointState,
  TaskCheckpointState,
  CheckpointMetadata,
  SerializedCheckpoint,
  CompressionInfo,
  EncryptionInfo,
  CheckpointStorageResult,
  CheckpointStorageError,
  CheckpointQueryOptions,
  CheckpointFilter,
  RetentionPolicyResult,
  CheckpointLineage,
  CheckpointStorageCapabilities,
  CheckpointStorageAdapterConfig,
  StorageOptions,
  CheckpointStorageHealthStatus,
  CheckpointProvider,
  CheckpointConfigValidationResult,
  CheckpointProviderMetadata,
  CompressedData,
  EncryptedData,
} from './checkpoints/checkpoint-storage.contract';

// Checkpoint storage runtime values (enums)
export {
  CheckpointType,
  SerializationFormat,
  CompressionAlgorithm,
  EncryptionAlgorithm,
  StorageType,
  RetentionPolicyScope,
} from './checkpoints/checkpoint-storage.contract';

// Checkpoint storage aliased types
export type {
  CheckpointRetentionPolicy as CheckpointRetentionPolicyConfig,
  SerializationOptions as CheckpointSerializationOptions,
  CompressionOptions as CheckpointCompressionOptions,
  EncryptionOptions as CheckpointEncryptionOptions,
  RetentionOptions as CheckpointRetentionOptions,
} from './checkpoints/checkpoint-storage.contract';

// Streaming adapters
export type {
  StreamingAdapter,
  StreamTransport,
  StreamSession,
  StreamSubscription,
  StreamChunk,
  ChunkHeaders,
  ChunkMetadata,
  ChunkFilter,
  ChunkHandler,
  StreamingError,
  StreamingCapabilities,
  StreamingAdapterConfig,
  BackpressureOptions,
  StreamingHealthStatus,
  StreamProvider,
  StreamConfigValidationResult,
  StreamProviderMetadata,
  ResumableStream,
  MultiplexedStream,
  SubStream,
  SubStreamOptions,
} from './streaming/streaming.contract';

// Streaming runtime values (enums)
export {
  StreamType,
  StreamStatus,
  ChunkType,
  SubscriptionStatus,
  BackpressureStrategy,
  StreamTransportType,
  ConnectionStatus,
} from './streaming/streaming.contract';

// Streaming aliased types
export type {
  BackpressureStrategy as StreamBackpressureStrategy,
  StreamSession as StreamingStreamSession,
  StreamType as StreamingStreamType,
  StreamStatus as StreamingStreamStatus,
  StreamMetadata as StreamingStreamMetadata,
  StreamOptions as StreamingStreamOptions,
  StreamSubscription as StreamingStreamSubscription,
  SubscriptionStatus as StreamingSubscriptionStatus,
  SubscribeOptions as StreamingSubscribeOptions,
  PublishOptions as StreamingPublishOptions,
  PublishResult as StreamingPublishResult,
  ConnectionStatus as StreamingConnectionStatus,
  TransportOptions as StreamingTransportOptions,
  SecurityOptions as StreamingSecurityOptions,
  AuthenticationConfig as StreamingAuthenticationConfig,
  EncryptionConfig as StreamingEncryptionConfig,
  TLSConfig as StreamingTLSConfig,
  StreamFilter as StreamingStreamFilter,
} from './streaming/streaming.contract';

// Worker runtime adapters
export type {
  WorkerRuntimeAdapter,
  WorkerHost,
  WorkerLease,
  WorkerLifecycle,
  WorkerHostConfig,
  WorkerResourceLimits,
  NetworkConfig,
  StorageConfig,
  StorageMount,
  WorkerHostMetadata,
  WorkerAffinity,
  NodeAffinity as WorkerNodeAffinity,
  NodeSelectorTerm as WorkerNodeSelectorTerm,
  NodeSelectorRequirement as WorkerNodeSelectorRequirement,
  PreferredSchedulingTerm as WorkerPreferredSchedulingTerm,
  PodAffinity as WorkerPodAffinity,
  PodAffinityTerm as WorkerPodAffinityTerm,
  LabelSelector as WorkerLabelSelector,
  LabelSelectorRequirement as WorkerLabelSelectorRequirement,
  WeightedPodAffinityTerm as WorkerWeightedPodAffinityTerm,
  HeartbeatResult,
  WorkerRuntimeError,
  WorkerStatus,
  WorkerRuntimeCapabilities,
  WorkerRuntimeAdapterConfig,
  HostConfig,
  LeaseConfig as WorkerLeaseConfig,
  HeartbeatConfig as WorkerHeartbeatConfig,
  LifecycleConfig as WorkerLifecycleConfig,
  WorkerHostFilter,
  WorkerRuntimeHealthStatus,
  WorkerProvider,
  WorkerConfigValidationResult,
  WorkerProviderMetadata,
  CheckpointAwareWorker,
  WorkerCheckpoint,
  WorkerState,
  GracefulShutdown,
  ShutdownOptions as WorkerShutdownOptions,
  ShutdownResult as WorkerShutdownResult,
  ShutdownStatus as WorkerShutdownStatus,
} from './workers/worker-runtime.contract';

// Worker runtime values (enums)
export {
  WorkerIsolationMode,
  WorkerHostType,
  WorkerHostStatus,
  NodeSelectorOperator as WorkerNodeSelectorOperator,
  LabelSelectorOperator as WorkerLabelSelectorOperator,
  WorkerStatus as WorkerWorkerStatus,
  ShutdownState as WorkerShutdownState,
} from './workers/worker-runtime.contract';

// Scheduling adapters
export type {
  SchedulingAdapter,
  SchedulingBackend,
  RuntimeSchedule,
  SchedulingLease,
  SchedulingDecision,
  SchedulingTopology,
  ScheduleExpression,
  ScheduleMetadata,
  SchedulingConstraints,
  ResourceConstraints as SchedulingResourceConstraints,
  AffinityConstraints as SchedulingAffinityConstraints,
  NodeAffinity as SchedulingNodeAffinity,
  NodeSelectorTerm as SchedulingNodeSelectorTerm,
  NodeSelectorRequirement as SchedulingNodeSelectorRequirement,
  NodeSelectorOperator as SchedulingNodeSelectorOperator,
  PreferredSchedulingTerm as SchedulingPreferredSchedulingTerm,
  PodAffinity as SchedulingPodAffinity,
  PodAffinityTerm as SchedulingPodAffinityTerm,
  LabelSelector as SchedulingLabelSelector,
  LabelSelectorRequirement as SchedulingLabelSelectorRequirement,
  LabelSelectorOperator as SchedulingLabelSelectorOperator,
  WeightedPodAffinityTerm as SchedulingWeightedPodAffinityTerm,
  ConcurrencyConstraints as SchedulingConcurrencyConstraints,
  TimeConstraints,
  ScheduleResult,
  SchedulingError,
  ScheduleUpdate,
  ScheduleFilter as SchedulingScheduleFilter,
  LeaseOptions as SchedulingLeaseOptions,
  SchedulingContext,
  TopologyNode,
  NodeType as SchedulingNodeType,
  NodeStatus as SchedulingNodeStatus,
  TopologyEdge,
  TopologyMetadata,
  SchedulingCapabilities,
  SchedulingAdapterConfig,
  SchedulingConfig,
  LeaseConfig as SchedulingAdapterLeaseConfig,
  TopologyConfig,
  FairnessConfig,
  WeightConfig,
  SchedulingHealthStatus,
} from './scheduling/scheduling.contract';

// Scheduling runtime values (enums)
export {
  ScheduleType,
  SchedulingPolicy,
  DecisionType,
  NodeType,
  NodeStatus,
  TopologyType,
  FairnessAlgorithm,
  SchedulingBackendType,
  ConnectionStatus as SchedulingConnectionStatus,
} from './scheduling/scheduling.contract';

// Scheduling aliased types
export type {
  ScheduleConfigValidationResult,
  SchedulingProviderMetadata,
} from './scheduling/scheduling.contract';

// Metrics adapters
export type {
  MetricsAdapter,
  MetricsBackend,
  RuntimeMetric,
  MetricType,
  MetricLabels,
  RuntimeCounter,
  CounterOptions,
  RuntimeGauge,
  GaugeOptions,
  RuntimeHistogram,
  HistogramOptions,
  MetricRecord,
  MetricAggregation,
  AggregationType,
  TimeRange as MetricsTimeRange,
  AggregationOptions,
  ExportOptions,
  ExportFormat,
  MetricsExportResult,
  MetricFilter,
  MetricsCapabilities,
  MetricsAdapterConfig,
  BackendConfig,
  MetricsBackendType,
  AggregationConfig as MetricsAggregationConfig,
  ExportConfig as MetricsExportConfig,
  LabelingConfig,
  MetricsHealthStatus,
  MetricsError,
  ConnectionStatus as MetricsConnectionStatus,
  MetricsProvider,
  MetricsConfigValidationResult,
  MetricsProviderMetadata,
  MetricsExporter,
  TracesToMetricsLinkage,
  ExecutionMetrics,
  ExecutionStatus as MetricsExecutionStatus,
  ExecutionMetricSummary,
  WorkerMetrics,
  WorkerStatus as MetricsWorkerStatus,
  WorkerMetricSummary,
  StreamingMetrics,
  StreamStatus as MetricsStreamStatus,
  StreamingMetricSummary,
} from './metrics/metrics.contract';

// Registry
export type {
  AdapterRegistry,
  AdapterDescriptor,
  AdapterResolver,
  CapabilityResolver,
  ProviderRegistry,
  AdapterCapabilities,
  AdapterLimitation,
  AdapterRequirement,
  AdapterConfiguration,
  ConfigurationSchema,
  PropertySchema,
  AdapterStatus as RegistryAdapterStatus,
  AdapterMetadata as RegistryAdapterMetadata,
  AdapterFilter,
  AdapterRequirements,
  VersionConstraints,
  ConfigurationRequirements,
  AdapterResolutionResult,
  ResolutionStrategy,
  ProviderDescriptor,
  ProviderCapabilities as RegistryProviderCapabilities,
  ProviderDependency,
  ProviderMetadata as RegistryProviderMetadata,
  ProviderFilter,
  ProviderRequirements,
  ProviderResolutionResult,
  CapabilityCompatibilityResult,
  FallbackReason,
  VersionCompatibilityResult,
  RegistryError,
  RegistryHealthStatus,
  ResolutionCache,
  ResolutionCacheEntry,
  CapabilityResolutionResult,
  CapabilityNegotiationResult,
  NegotiationStrategy,
  CapabilityMatrix,
  CompatibilityValidationResult as RegistryCompatibilityValidationResult,
} from './registry/registry.contract';

// Factory
export type {
  AdapterFactory,
  AdapterBootstrapper,
  AdapterLifecycleManager,
  DependencyWiring,
  LazyLoadingSemantics,
  AdapterFactoryConfig,
  AdapterDependency,
  DependencyType,
  AdapterLifecycleConfig,
  AdapterFactoryResult,
  FactoryError,
  ConfigValidationResult,
  AdapterFactoryFilter,
  AdapterFactoryStatus,
  AdapterFactoryContext,
  RuntimeEnvironment,
  FactoryConfiguration,
  AdapterDependencyGraph,
  DependencyNode,
  DependencyEdge,
  FactoryMetadata,
  FactoryHealthStatus,
  BootstrapConfig,
  BootstrapResult,
  BootstrapStatus,
  BootstrapState,
  LifecycleResult,
  LifecycleState,
  LifecycleEvent,
  LifecycleEventType,
  LifecycleEventHandler,
  LifecycleSubscription,
  WiringResult,
  DependencyGraph,
  DependencyGraphNode,
  DependencyGraphEdge,
  WiringValidationResult,
  CircularDependency,
  LazyLoadResult,
  LazyLoadStatus,
  LazyLoadState,
  RuntimeBootstrapConfig,
  BootstrapOrder,
  ParallelizationConfig,
  RuntimeBootstrapResult,
  BootstrapProgress,
  RuntimeStatus,
  RuntimeBootstrapManager as RuntimeBootstrapOrchestrator,
} from './factory/factory.contract';
