/**
 * CLAUX V1 Canonical Command Center Task Types
 * Simple, deterministic types for command center tasks
 * NO abstractions, NO enterprise patterns
 */

import type { TaskType, TaskPriority } from '@/lib/command-center/types';

/**
 * Command Center Task
 * Human-executable task generated by agents
 */
export interface CommandCenterTask {
  task_type: TaskType;
  title: string;
  description: string;
  priority: TaskPriority;
  action_payload: Record<string, unknown>;
  recommended_action?: string;
  client_visible_impact?: string;
}

/**
 * ARIA Command Tasks
 */
export interface AriaKeywordReviewTask extends CommandCenterTask {
  task_type: 'keyword_review';
  action_payload: {
    keyword: string;
    difficulty: number;
    search_volume: number;
  };
}

/**
 * SCRIBE Command Tasks
 */
export interface ScribeContentReviewTask extends CommandCenterTask {
  task_type: 'content_review';
  action_payload: {
    article_title: string;
    word_count: number;
  };
}

export interface ScribePublishingPackageTask extends CommandCenterTask {
  task_type: 'publishing_package';
  action_payload: {
    slug: string;
    meta_title: string;
  };
}

export interface ScribeSchemaImplementationTask extends CommandCenterTask {
  task_type: 'schema_implementation';
  action_payload: {
    schema_type: string;
  };
}

/**
 * PUBLISH Command Tasks
 * Uses existing canonical TaskType values
 */
export interface PublishUploadTask extends CommandCenterTask {
  task_type: 'publishing_package';
  action_payload: {
    slug: string;
    title: string;
    content: string;
  };
}

export interface PublishImageTask extends CommandCenterTask {
  task_type: 'publishing_package';
  action_payload: {
    image_prompt: string;
    alt_text: string;
  };
}

export interface PublishInternalLinksTask extends CommandCenterTask {
  task_type: 'internal_linking';
  action_payload: {
    internal_links: Array<{
      url: string;
      anchor_text: string;
    }>;
  };
}

/**
 * PULSE Command Tasks
 * Uses existing canonical TaskType values
 */
export interface PulseRankingMonitorTask extends CommandCenterTask {
  task_type: 'keyword_review';
  action_payload: {
    keyword: string;
    current_position: number;
    previous_position: number;
  };
}

/**
 * LOCL Command Tasks
 */
export interface LoclGmbOptimizationTask extends CommandCenterTask {
  task_type: 'gmb_optimization';
  action_payload: {
    location_id: string;
    optimization_type: string;
  };
}

export interface LoclCitationTask extends CommandCenterTask {
  task_type: 'citation_building';
  action_payload: {
    citation_source: string;
    business_name: string;
  };
}

/**
 * REPUTE Command Tasks
 */
export interface ReputeReviewReplyTask extends CommandCenterTask {
  task_type: 'review_reply';
  action_payload: {
    platform: string;
    review_id: string;
    suggested_reply: string;
  };
}

/**
 * LINX Command Tasks
 */
export interface LinxOutreachTask extends CommandCenterTask {
  task_type: 'backlink_outreach';
  action_payload: {
    target_domain: string;
    outreach_email: string;
    outreach_template: string;
  };
}

/**
 * PRISM Command Tasks
 * Uses existing canonical TaskType values
 */
export interface PrismAnalyticsReviewTask extends CommandCenterTask {
  task_type: 'content_audit';
  action_payload: {
    metric: string;
    trend: 'up' | 'down' | 'stable';
    value: number;
  };
}

/**
 * CORE Command Tasks
 * Uses existing canonical TaskType values
 */
export interface CoreTechnicalFixTask extends CommandCenterTask {
  task_type: 'technical_audit';
  action_payload: {
    issue_type: string;
    url: string;
    fix_instructions: string;
  };
}

export interface CoreSchemaFixTask extends CommandCenterTask {
  task_type: 'schema_validation';
  action_payload: {
    schema_type: string;
    url: string;
    schema_json: Record<string, unknown>;
  };
}
