/**
 * Publish Package Types
 *
 * Canonical structure for SCRIBE publishing packages
 * V1 prohibits CMS automation - packages are for human review only
 */

/**
 * Publish Package
 * Complete publishing package generated by SCRIBE
 * Stored in action_payload JSONB for human review
 */
export interface PublishPackage {
  title: string;
  slug: string;
  meta_title: string;
  meta_description: string;
  schema_json: Record<string, unknown>;
  featured_image_prompt: string;
  internal_linking: InternalLinkSuggestion[];
  recommended_category: string;
  recommended_tags: string[];
  content_markdown: string;
  seo_notes: string[];
}

/**
 * Internal Link Suggestion
 * Suggested internal links for the content
 */
export interface InternalLinkSuggestion {
  target_url: string;
  anchor_text: string;
  relevance_score: number;
  context: string;
}

/**
 * Schema JSON Structure
 * Canonical schema.org markup structure
 */
export interface SchemaMarkup {
  '@context': string;
  '@type': string;
  headline?: string;
  description?: string;
  author?: {
    '@type': string;
    name: string;
  };
  datePublished?: string;
  dateModified?: string;
  mainEntityOfPage?: {
    '@type': string;
    '@id': string;
  };
  [key: string]: unknown;
}
